# wrangler.toml
name = "cf-worker-mtls-browser-test" # Можеш змінити, якщо хочеш іншу назву для воркера
main = "index.js"                     # Шлях до головного файлу
compatibility_date = "2025-04-30"     # ВАЖЛИВО: Вкажи поточну дату у форматі РРРР-ММ-ДД
